server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot2
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
    fetch-registry: true
    register-with-eureka: true
